import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import '@/styles/main.scss';

const lato = Lato({ subsets: ['latin'], weight: ['300', '400'] });

export const metadata: Metadata = {
  title: 'Rule of Thumb',
  description: 'Generated by Jhon Moreno',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>{children}</body>
    </html>
  );
}
